[run]
init_cmds = [
	["go", "install"],
	["go", "build"],
	["./orbiter"]
]
watch_all = true
watch_dirs = [
	"models",
	"modules",
	"routers"
]
watch_exts = [".go"]
cmds = [
	["go", "install"],
	["go", "build"],
	["./orbiter"]
]