version: '3'

vars:
  NAME: orbiter
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d %I:%M:%S %Z'
  BUILD_COMMIT:
    sh: git rev-parse HEAD

tasks:
  default:
    cmds:
      - task: web

  web:
    desc: Build the binary and start the web server
    deps: [build]
    cmds:
      - ./{{.NAME}}

  build:
    desc: Build binary
    cmds:
      - go build -ldflags '-X unknwon.dev/orbiter/internal/setting.Version={{.BUILD_COMMIT}}' -v -trimpath -o {{.NAME}}
    sources:
      - ./*.go
      - internal/**/*.go

  clean:
    desc: Clean up meta and packed files
    cmds:
      - go clean
